config/routes.rb
Rails.application.routes.draw do

  # ルートのルーティング
  root 'tops#index'

  get 'anime', to: 'tops#show', as: 'anime' # アニメーションのルーティング
  get 'trial', to: 'trials#index', as: 'trial' # お試しページを表示するためのルーティング

  # top(トップ)のルーティング
  scope :tops, controller: :tops do
    post :tos, as: :tops_tos
    post :pp, as: :tops_pp
    post :enter_app, as: :tops_enter_app
    post :login, as: :tops_login
  end

  # Deviseのルーティング
  devise_for :users, skip: [:sessions], controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    post 'users/auth/google_oauth2/callback', to: 'users/omniauth_callbacks#google_oauth2'
    get '/users/sign_in', to: redirect('/')  # 暫定　ソーシャルログインだけの場合
    delete 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  # dashboard(ダッシュボード)のルーティング
  authenticate :user do
    resources :dashboards, only: [:index] do
      collection do
        post :menu, to: 'dashboards#menu'
        post :close_menu, to: 'dashboards#close_menu'
        post :info, to: 'dashboards#info'
        post :reset_gift, to: 'dashboards#reset_gift_notifications'
      end
    end
  end

  # search(検索)のルーティング
  scope :search, controller: :search do
    post :search_response
    post :search
  end

  # consultation(コンサルテーション)のルーティング
  resources :consultations, only: [:show, :edit, :update, :create, :destroy] do
    member do
      post 'response', to: 'consultations#consultations_response', as: :response
      get 'select_tone', to: 'consultations#select_tone'
    end
  
    collection do
      post 'worries', to: 'consultations#worries'
      post 'detail', to: 'consultations#consultations_detail'
      post 'consultations_category/:category_id', to: 'consultations#consultations_category'
    end
  
    resources :replies, only: [:new, :create, :destroy]
  end

  # gift(ギフト)のルーティング
  resources :gifts do
    collection do
      post 'all', to: 'gifts#gift_all'
      post 'list', to: 'gifts#gift_list'
      post 'send_gift_response', to: 'gifts#send_gift_response'
    end
  
    member do
      patch :mark_as_read
      post 'send_gift', to: 'gifts#send_gift'
    end
  end
  
  resources :menus1, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    collection do
      get :gift_list
    end
  end

  # (chat)チャットのルーティング
  resources :chats, only: [:index, :show, :create, :destroy]  do
    collection do
      post 'chat', to: 'chats#chat'
    end
  end

  # (groupchat)グループチャットのルーティング
  resources :group_chats, only: [:new, :index, :edit, :create, :update, :destroy] do
    member do
      post 'add_member', to: 'group_chats#add_member'
      post 'group_chat', to: 'group_chats#group_chat'
      post 'group_chat_list' , to: 'group_chats#group_chat_list'
    end
    # グループチャットのメンバーのルーティング
    resources :group_chat_members, only: [:new, :create, :update, :destroy]
    # グループチャットのメッセージのルーティング
    resources :group_chat_messages, only: [:create, :destroy]
  end

  #User(ユーザー)のルーティング
  resources :users, only: [:show, :update, :destroy] do
    collection do
      post 'user_list', to: 'users#user_list'
      post 'user_list_show', to: 'users#user_list_show'
    end
    member do
      get 'edit', to: 'users#edit', as: 'edit_user_profile'
    end
  end

  # admin(管理画面)のルート
  authenticate :user, ->(u) { u.super_admin? } do
    namespace :admin do
      resources :users, only: [:destroy]
      resources :consultations, only: [:destroy]
      resources :gifts, only: [:destroy]
      get 'dashboards', to: 'dashboards#index'
      post 'dashboards', to: 'dashboards#redirect_to_dashboard'
      resources :admin_users, only: [:index, :edit, :update, :destroy]
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2, :discord, :twitter, :github, :line]

  before_create :generate_random_display_name # 追加

  has_many :admin_users
  has_many :organizations, through: :admin_users
  has_many :organizations, through: :user_organizations
  has_many :sent_chats, class_name: 'Chat', foreign_key: 'sender_id'
  has_many :received_chats, class_name: 'Chat', foreign_key: 'receiver_id'
  has_many :consultations, dependent: :destroy
  has_many :sent_gifts, class_name: 'Gift', foreign_key: 'giver_id', dependent: :nullify
  has_many :received_gifts, class_name: 'Gift', foreign_key: 'receiver_id', dependent: :nullify
  has_many :group_chat_members, dependent: :destroy
  has_many :group_chat_messages, dependent: :destroy
  belongs_to :organization, optional: true
  has_one :profile, dependent: :destroy
  accepts_nested_attributes_for :profile
  has_many :replies, dependent: :destroy
  has_many :user_organizations, dependent: :destroy
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  after_create :assign_initial_gifts

  # ユーザーが管理者かどうかを判定するメソッド
  def admin?
    admin_users.exists?
  end

  # ユーザーが特定の組織の管理者かどうかを判定するメソッド
  def admin_for?(organization)
    admin_users.exists?(organization: organization)
  end

  # ユーザーがスーパー管理者かどうかを判定するメソッド
  def super_admin?
    admin_users.exists?(admin_role: :super_admin)
  end

  # 特定の返信者から受け取ったギフトを取得するメソッド
  def received_gifts_from_repliers
    replier_ids = consultations.joins(:replies).pluck('replies.user_id').uniq
    received_gifts.where(giver_id: replier_ids)
  end

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first_or_initialize
  
    if user.new_record?
      # 新規ユーザーの場合のみ、名前と表示名を設定する
      user.name = data['name']
      user.display_name = data['nickname'] || data['name'] || user.generate_random_display_name
      user.password = Devise.friendly_token[0, 20]
      user.save
    end
  
    user
  end

  # ユーザーが持つ相談から、未読の返信数を返すメソッド
  def unread_replies_count
    Reply.joins(:consultation)
         .where(consultations: { user_id: id })
         .where(read: false) # read は返信が読まれたかどうかを示す属性
         .count
  end

  # 未読のギフト数を計算するメソッド
  def calculate_unread_gifts_count
    received_gifts_from_repliers.sum do |gift|
      gift.gift_histories.where(read: false).count + (gift.sender_message.present? ? 1 : 0)
    end
  end

  public

  def assign_initial_gifts
    gift_templates = GiftTemplate.order("RANDOM()").limit(10)
    gift_templates.each do |template|
      Gift.create!(
        gift_template_id: template.id,
        gift_category: template.gift_category,
        item_name: template.name,
        description: template.description,
        image_url: template.image_url,
        color: template.color,
        receiver_id: self.id,
        giver_id: nil,
        sent_at: nil
      )
    end
  end

  # ランダムな表示名を生成するメソッド
  def generate_random_display_name
    loop do
      random_name = SecureRandom.hex(5) # 10文字のランダムな表示名
      break self.display_name = random_name unless User.exists?(display_name: random_name)
    end
  end
end

app/controllers/admin/users_controller.rb
# app/controllers/admin/users_controller.rb
module Admin
  class UsersController < ApplicationController
    include ActionView::RecordIdentifier

    before_action :set_user, only: [:destroy]

    def destroy
      ActiveRecord::Base.transaction do
        @user.sent_chats.destroy_all
        @user.received_chats.destroy_all
        @user.destroy
      end
      respond_to do |format|
        format.turbo_stream { render turbo_stream: turbo_stream.remove(dom_id(@user)) }
        format.html { redirect_to admin_dashboards_path, notice: 'ユーザーを削除しました。' }
      end
    rescue ActiveRecord::RecordNotDestroyed => e
      respond_to do |format|
        format.html { redirect_to admin_dashboards_path, alert: 'ユーザーの削除に失敗しました。' }
      end
    end

    private

    def set_user
      @user = User.find(params[:id])
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    handle_auth "Google"
  end

  def twitter
    handle_auth "Twitter"
  end

  def github
    handle_auth "GitHub"
  end

  def line
    handle_auth "LINE"
  end

  def discord
    handle_auth "Discord"
  end

  def handle_auth(kind)
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.nil?
      flash[:alert] = I18n.t('devise.omniauth_callbacks.failure', kind: kind, reason: "作成または検索できませんでした")
      redirect_to new_user_registration_url
    elsif @user.persisted?
      if @user.previous_changes[:id].present?

        @user.update!(display_name: @user.generate_random_display_name) if @user.display_name.blank?
        @user.assign_initial_gifts

        flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: kind)
        sign_in(@user)
        redirect_to edit_user_profile_user_path(@user)
      else
        flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: kind)
        sign_in_and_redirect @user, event: :authentication
      end
    else
      session["devise.#{kind}_data"] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def user_list
    @users = User.all
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.replace("content", partial: "user_response"),
          turbo_stream.replace('unread-replies-count', partial: 'layouts/unread_replies_count', locals: { user: current_user }),
          turbo_stream.replace("unread-gifts-count", partial: "layouts/unread_gifts_count", locals: { unread_gifts_count: @unread_gifts_count })
        ]
      end
    end
  end

  def user_list_show
    @user = User.find(params[:id])
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.replace("content", partial: "user_show_response")
        ]
      end
    end
  end

  def show
    @user = User.find(params[:id])
    @sent_gifts = @user.sent_gifts
    replier_ids = @user.consultations.joins(:replies).pluck('replies.user_id').uniq
    @received_gifts_from_repliers = @user.received_gifts.where(giver_id: replier_ids)

    mark_gift_comments_and_messages_as_read(@received_gifts_from_repliers)
  end

  def edit
    @user = User.find(params[:id])
    @user.build_profile unless @user.profile
  end

  def update
    if @user.update(user_params)
      redirect_to dashboard_path, notice: 'ユーザーは正常に更新されました。'
    else
      Rails.logger.debug @user.errors.full_messages
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path, notice: 'ユーザーが正常に削除されました。'
  end

  private

  def set_user
    @user = User.find_by(id: params[:id])
    unless @user && (@user == current_user || current_user.admin?)
      redirect_to root_url, alert: "Access denied."
    end
  end

  def user_params
    params.require(:user).permit(:name, :email, :display_name, profile_attributes: [:introduction, :interests])
  end

  def mark_gift_comments_and_messages_as_read(gifts)
    gifts.each do |gift|
      gift.gift_histories.where(read: false).update_all(read: true)
      gift.update(sender_message: nil) if gift.sender_message.present?
    end
  end
end

app/views/users/_user_button.html.erb
<%= button_to 'ユーザーの一覧', user_list_users_path, method: :post, class: 'button is-primary is-small column is-full mt-5 button-wrap-text' %>

app/views/users/_user_response.html.erb
<div id="content" class="container is-small ml-5">
  <div class="columns is-multiline user-fixed-height">
    <% @users.each do |user| %>
      <div class="column is-one-third">
        <div class="card">
          <div class="card-content has-text-white">
            <p class="title is-5">名前: <%= user.name %></p>
          </div>
          <footer class="card-footer">
            <div class="card-footer-item">
              <div class="is-pulled-right buttons-right">
                <%= button_to '詳細を見る', user_list_show_users_path(id: user.id), method: :post, class: 'button is-primary is-small' %>
              </div>
            </div>
          </footer>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/_user_show_response.html.erb
<div id="content" class="container is-small">
  <div class ="user-fixed-height">
    <div class="card">
      <div class="card-content">
        <div class="is-flex buttons-right is-justify-content-space-between is-align-items-center m-3">
          <p class="title is-size-4-mobile">
            名前: <%= @user.name %>
          </p>
          <%= button_to '戻る', user_list_users_path, method: :post, class: 'button is-primary' %>
        </div>
        <p class="subtitle is-size-5-mobile m-3">組織: <%= @user.organization&.name || '未登録' %></p>
        <p class="subtitle is-size-5-mobile m-3">自己紹介: <%= @user.profile&.introduction || '未登録' %></p>
        <p class="subtitle is-size-5-mobile m-3">興味・関心: <%= @user.profile&.interests || '未登録' %></p>
        <p class="m-3"><strong>ギフトを贈った回数：</strong><%= @user.sent_gifts.count %></p>
        <p class="m-3"><strong>送ったギフト：</strong></p>
        <ul class="mt-3">
          <% @user.sent_gifts.each do |gift| %>
              <li><%= gift.item_name %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="user-show container is-small">

  <%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
      <div class="notification is-danger">
        <h2><%= pluralize(@user.errors.count, "エラー") %>が発生しました:</h2>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field mt-1">
      <%= f.label :name, "名前", class: 'label' %>
      <%= f.text_field :name, class: 'input', placeholder: '名前を入力してください' %>
    </div>

    <div class="field">
      <%= f.label :display_name, "プライベートチャット用表示名", class: 'label' %>
      <%= f.text_field :display_name, class: 'input', readonly: true %>
    </div>

    <div class="field">
      <%= f.label :email, "メールアドレス", class: 'label' %>
      <%= f.email_field :email, class: 'input', placeholder: 'メールアドレスを入力してください' %>
    </div>

    <%= f.fields_for :profile do |p| %>
      <div class="field">
        <%= p.label :introduction, "自己紹介", class: 'label' %>
        <%= p.text_area :introduction, class: 'textarea', placeholder: '自己紹介を入力してください' %>
      </div>

      <div class="field">
        <%= p.label :interests, "興味・関心", class: 'label' %>
        <%= p.text_area :interests, class: 'textarea', placeholder: '興味・関心を入力してください' %>
      </div>
    <% end %>
    <div class="user-buttons-right" >
    <div class="field is-flex is-justify-content-flex-end mt-2">
      <%= f.submit "更新", class: 'button is-primary is-small' %>
      <%= link_to '戻る', user_path(current_user), class: 'button is-info is-small ml-2' %>
    </div>
    </div>
  <% end %>

</div>

app/views/users/show.html.erb
<div data-controller="modal">
  <div class="user-show container is-small mt-3">
    <div class="card">
      <header class="card-header">
        <p class="card-header-title">ユーザープロフィール</p>
      </header>
      <div class="card-content">
        <div class="content">
          <div class="columns">
            <div class="column">
              <p><strong>名前：</strong> <%= @user.name %></p>
              <p><strong>プライベートチャット表示名：</strong> <%= @user.display_name %></p>
              <p><strong>メール：</strong> <%= @user.email %></p>
              <p><strong>組織：</strong> <%= @user.organization&.name || '未登録' %></p>
              <p><strong>自己紹介：</strong> <%= @user.profile&.introduction || '未登録' %></p>
              <p><strong>興味・関心：</strong> <%= @user.profile&.interests || '未登録' %></p>
            </div>
          </div>
          <hr>
          <div class="content">
            <h2 class="title is-4">相談の詳細</h2>
            <p><strong>相談への返信：</strong></p>
            <ul>
              <% @user.consultations.each do |consultation| %>
                <% consultation.replies.each do |reply| %>
                  <li>返信者: <%= reply.display_name %>さん, 返信内容: <%= reply.content %></li>
                <% end %>
              <% end %>
            </ul>
          </div>
          <hr>
          <div class="content">
            <h2 class="title is-4">ギフトの詳細</h2>
            <p><strong>贈ったギフトと回数：</strong> <%= @user.sent_gifts.count %></p>
            <ul>
              <% @user.sent_gifts.each do |gift| %>
                <li><%= gift.item_name %></li>
              <% end %>
            </ul>
            <p><strong>相談の返信者から受け取ったギフト：</strong> <%= @received_gifts_from_repliers.count %></p>
            <ul>
              <% @received_gifts_from_repliers.each do |gift| %>
                <% if gift.item_name.present? && (gift.sender_message.present? || gift.gift_histories.any? { |history| history.sender_message.present? }) %>
                  <li>
                    <p><strong>ギフト名:</strong> <%= gift.item_name %></p>
                    <p><strong>花言葉or宝石言葉:</strong> <%= gift.description %></p>
                    <% if gift.giver.present? %>
                      <p>送り主: <%= gift.giver.name %>さん</p>
                    <% end %>
                    <% if gift.image_url.present? %>
                      <figure class="image is-128x128">
                        <%= image_tag gift.image_url, alt: "ギフトの画像", data: { action: "click->modal#open" } %>
                      </figure>
                    <% end %>
                    <% if gift.gift_histories.any? %>
                      <% gift.gift_histories.each do |history| %>
                        <% if history.sender_message.present? %>
                          <p>メッセージ: <%= history.sender_message %></p>
                        <% end %>
                      <% end %>
                    <% elsif gift.sender_message.present? %>
                      <p>メッセージ: <%= gift.sender_message %></p>
                    <% end %>
                    <%
                      app_url = "https://www.xn--z8j3e5a2787akv3apqn.com"
                      tweet_message = "相談のお礼に「#{ERB::Util.url_encode(gift.item_name)}」を受け取りました！%0A花言葉or宝石言葉:「 #{ERB::Util.url_encode(gift.description)}」の意味が込められてます。%0A%23めぐる宝石花%0A#{ERB::Util.url_encode(app_url)}"
                    %>
                    <div class="field is-grouped custom-left buttons-right mb-6">
                      <div class="twitter custom-left">
                        <%= link_to "https://twitter.com/intent/tweet?text=#{tweet_message}", target: "_blank", class: "button is-info button-wrap-text ml-2 tooltip", data: { tooltip: "ツイートを投稿" } do %>
                          <i class="fab fa-twitter twitter-icon"></i>
                        <% end %>
                      </div>
                    </div>
                  </li>
                <% end %>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="user-show-button user-buttons-right container is-small">
    <div class="is-small is-flex is-justify-content-flex-end mt-2">
      <%= link_to '編集', edit_user_profile_user_path(@user), class: 'button is-link is-small' %>
      <%= link_to '戻る', dashboards_path, class: 'button is-info is-small ml-2' %>
    </div>
  </div>
  <div data-modal-target="modalContainer" class="modal">
    <div class="modal-background"></div>
    <div class="modal-content">
      <p class="image">
        <img data-modal-target="modalImage" src="" alt="拡大画像" class="is-clickable">
      </p>
    </div>
    <button class="modal-close is-large" aria-label="close" data-action="click->modal#close"></button>
  </div>
</div>