config/routes.rb
Rails.application.routes.draw do

  # ルートのルーティング
  root 'tops#index'

  get 'anime', to: 'tops#show', as: 'anime' # アニメーションのルーティング
  get 'trial', to: 'trials#index', as: 'trial' # お試しページを表示するためのルーティング

  # top(トップ)のルーティング
  scope :tops, controller: :tops do
    post :tos, as: :tops_tos
    post :pp, as: :tops_pp
    post :enter_app, as: :tops_enter_app
    post :login, as: :tops_login
  end

  # Deviseのルーティング
  devise_for :users, skip: [:sessions], controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    post 'users/auth/google_oauth2/callback', to: 'users/omniauth_callbacks#google_oauth2'
    get '/users/sign_in', to: redirect('/')  # 暫定　ソーシャルログインだけの場合
    delete 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  # dashboard(ダッシュボード)のルーティング
  authenticate :user do
    resources :dashboards, only: [:index] do
      collection do
        post :menu, to: 'dashboards#menu'
        post :close_menu, to: 'dashboards#close_menu'
        post :info, to: 'dashboards#info'
        post :reset_gift, to: 'dashboards#reset_gift_notifications'
      end
    end
  end

  # search(検索)のルーティング
  scope :search, controller: :search do
    post :search_response
    post :search
  end

  # consultation(コンサルテーション)のルーティング
  resources :consultations, only: [:show, :edit, :update, :create, :destroy] do
    member do
      post 'response', to: 'consultations#consultations_response', as: :response
      get 'select_tone', to: 'consultations#select_tone'
    end
  
    collection do
      post 'worries', to: 'consultations#worries'
      post 'detail', to: 'consultations#consultations_detail'
      post 'consultations_category/:category_id', to: 'consultations#consultations_category'
    end
  
    resources :replies, only: [:new, :create, :destroy]
  end

  # gift(ギフト)のルーティング
  resources :gifts do
    collection do
      post 'all', to: 'gifts#gift_all'
      post 'list', to: 'gifts#gift_list'
      post 'send_gift_response', to: 'gifts#send_gift_response'
    end
  
    member do
      patch :mark_as_read
      post 'send_gift', to: 'gifts#send_gift'
    end
  end
  
  resources :menus1, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    collection do
      get :gift_list
    end
  end

  # (chat)チャットのルーティング
  resources :chats, only: [:index, :show, :create, :destroy]  do
    collection do
      post 'chat', to: 'chats#chat'
    end
  end

  # (groupchat)グループチャットのルーティング
  resources :group_chats, only: [:new, :index, :edit, :create, :update, :destroy] do
    member do
      post 'add_member', to: 'group_chats#add_member'
      post 'group_chat', to: 'group_chats#group_chat'
      post 'group_chat_list' , to: 'group_chats#group_chat_list'
    end
    # グループチャットのメンバーのルーティング
    resources :group_chat_members, only: [:new, :create, :update, :destroy]
    # グループチャットのメッセージのルーティング
    resources :group_chat_messages, only: [:create, :destroy]
  end

  #User(ユーザー)のルーティング
  resources :users, only: [:show, :update, :destroy] do
    collection do
      post 'user_list', to: 'users#user_list'
      post 'user_list_show', to: 'users#user_list_show'
    end
    member do
      get 'edit', to: 'users#edit', as: 'edit_user_profile'
    end
  end

  # admin(管理画面)のルート
  authenticate :user, ->(u) { u.super_admin? } do
    namespace :admin do
      resources :users, only: [:destroy]
      resources :consultations, only: [:destroy]
      resources :gifts, only: [:destroy]
      get 'dashboards', to: 'dashboards#index'
      post 'dashboards', to: 'dashboards#redirect_to_dashboard'
      resources :admin_users, only: [:index, :edit, :update, :destroy]
    end
  end
end

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < Admin::ApplicationController
  def index
    @admin_users = AdminUser.includes(:user, :organization).all
    @current_time = Time.zone.now.in_time_zone('Asia/Tokyo')
    @group_chats = GroupChat.all
    @users = User.all
    @consultations = Consultation.all
    @gifts = Gift.includes(:gift_category).all
    @gift_histories = GiftHistory.all
    @gift_templates = GiftTemplate.includes(:gift_category).all
  end

  def destroy_user
    user = User.find(params[:id])
    user.destroy
    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove(dom_id(user)) }
      format.html { redirect_to admin_dashboards_index_path, notice: 'ユーザーを削除しました。' }
    end
  end

  def destroy_consultation
    consultation = Consultation.find(params[:id])
    consultation.destroy
    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove(dom_id(consultation)) }
      format.html { redirect_to admin_dashboards_index_path, notice: '相談を削除しました。' }
    end
  end

  def destroy_gift
    gift = Gift.find(params[:id])
    gift.destroy
    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove(dom_id(gift)) }
      format.html { redirect_to admin_dashboards_index_path, notice: 'ギフトを削除しました。' }
    end
  end

  def redirect_to_dashboard
    redirect_to admin_dashboard_path
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :set_common_variables, only: [:index, :info, :menu, :close_menu]
  before_action :set_latest_replies_and_notifications, only: [:index, :info]

  def index; end

  def info
    @current_time = Time.zone.now
    render_turbo_response("content", "info_response", {
      gifts: @gifts,
      replies: @replies,
      reply_users: @reply_users,
      latest_gift_messages: @latest_gift_messages,
      unread_gifts_count: @unread_gifts_count,
      unread_replies_count: @unread_replies_count,
      current_time: @current_time,
      group_chats: @group_chats,
      user: @user,
      latest_gifts: @latest_gifts,
      sent_gifts: @sent_gifts,
      received_gifts: @received_gifts
    })
  end

  def menu
    render_turbo_stream_for_menu("buttons/menu/menu_buttons")
  end

  def close_menu
    render_turbo_stream_for_menu("buttons/menu/closed_menu")
  end

  def search
    if params[:query].present? && params[:query].strip.present?
      queries = params[:query].split(/[\s　]+/)
      @consultations = queries.flat_map do |q|
        Consultation.search(q, fields: [:title, :content, :category_name, :user_name], match: :word_middle)
      end.uniq
    else
      @consultations = Consultation.none
    end
  end

  def reset_gift_notifications
    replier_ids = current_user.consultations.joins(:replies).pluck('replies.user_id').uniq
    @received_gifts_from_repliers = current_user.received_gifts.where(giver_id: replier_ids)
    mark_gift_comments_and_messages_as_read(@received_gifts_from_repliers)
    redirect_to dashboards_path, notice: '通知がリセットされました。'
  end

  private

  def set_common_variables
    @user = current_user
    @unread_gifts_count = @user.calculate_unread_gifts_count
    @unread_replies_count = fetch_unread_replies_count
    @gifts = @user.received_gifts
    @reply_users = User.joins(:replies).distinct
    @latest_gifts = Gift.order(created_at: :desc).limit(5)
    @sent_gifts = @user.sent_gifts
    @received_gifts = @user.received_gifts
    @latest_gift_messages = fetch_latest_gift_messages
    @group_chats = GroupChat.all
    @available_gift_items = @user.received_gifts.where(sent_at: nil).distinct.pluck(:item_name)
    
    @replies = fetch_latest_replies.map do |reply|
      {
        reply: reply,
        display_name: reply.display_name
      }
    end
  end

  def set_latest_replies_and_notifications
    @latest_replies = fetch_latest_replies
  end

  def fetch_latest_replies
    Reply.joins(:consultation, :user)
         .where(consultations: { user_id: current_user.id })
         .select('replies.*, users.name as user_name')
         .order('replies.created_at DESC')
         .limit(5)
  end

  def fetch_latest_gift_messages
    gift_messages = current_user.received_gifts.joins(:gift_histories).pluck('gift_histories.sender_message', 'gift_histories.created_at', 'gifts.id') +
                    current_user.received_gifts.pluck(:sender_message, :created_at, :id)
    gift_messages.reject { |message, _, _| message.blank? }
                 .sort_by { |_, created_at, _| created_at }
                 .reverse
                 .first(5)
                 .map do |message, created_at, gift_id|
                   gift = Gift.find(gift_id)
                   { message: message, created_at: created_at, gift: Gift.find(gift_id) }
                 end
  end

  def fetch_unread_replies_count
    current_user.consultations.joins(:replies).where(replies: { read: false }).count || 0
  end

  def mark_gift_comments_and_messages_as_read(gifts)
    gifts.each do |gift|
      gift.gift_histories.where(read: false).update_all(read: true)
      gift.update(sender_message: nil) if gift.sender_message.present?
    end
  end

  def render_turbo_response(target, partial, locals = {})
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace(target, partial: partial, locals: locals)
      end
    end
  end

  def render_turbo_stream_for_menu(menu_partial)
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.replace("menu", partial: menu_partial),
          turbo_stream.replace("content", partial: "buttons/response"),
          turbo_stream.replace('unread-replies-count', partial: 'layouts/unread_replies_count', locals: { user: current_user }),
          turbo_stream.replace("unread-gifts-count", partial: "layouts/unread_gifts_count", locals: { unread_gifts_count: @unread_gifts_count })
        ]
      end
    end
  end
end

app/views/dashboards/_info_button.html.erb
<% button_class = 'button is-small column is-full mt-5 button-wrap-text' %>
<% if @unread_gifts_count > 0 || @unread_replies_count > 0 %>
  <% button_class += ' is-warning' %>
<% else %>
  <% button_class += ' is-primary' %>
<% end %>

<%= button_to "最新の通知", info_dashboards_path, remote: true, method: :post, class: button_class %>

app/views/dashboards/_info_response.html.erb
<div id="content" class="info-fixed-height container is-small ml-5">
  <div class="card">
    <header class="card-header">
      <div class="columns is-vcentered is-mobile">
        <div class="column is-narrow">
          <strong class="is-size-4 ml-4 info-margin">最新の通知</strong>
          <p class="is-size-6 mr-6 ml-5 info-margin">
            最新のメッセージは、<span class="mobile-line-break"></span>5件のみ表示されています。<br>
          </p>
        </div>
      </div>
    </header>
    <div class="card-content">
      <div class="content">
        <div class="columns">
          <div class="column is-one-third">
            <div id="latest-messages" class="mb-2">
              <h3 class="custom-message-title">最新のメッセージ</h3>
              <% if @latest_replies.present? %>
                <ul>
                  <% @replies.each do |reply_hash| %>
                    <% reply = reply_hash[:reply] %>
                    <li>
                      <p><strong>返信者:</strong> <%= reply_hash[:display_name] %>さん</p>
                      <p><strong>返信内容:</strong> <%= reply_hash[:reply].content %></p>
                      <p><em>スタイル: <%= Reply.tones[reply.tone] %></em></p>
                      <p><strong>受信日時:</strong> <%= reply.created_at.in_time_zone('Asia/Tokyo').strftime("%Y-%m-%d %H:%M:%S") %></p>
                    </li>
                  <% end %>
                </ul>
              <% else %>
                <p>最新のメッセージはありません。</p>
              <% end %>
            </div>
          </div>
          <div class="column is-one-third">
            <h3>感謝の気持ちを伝える</h3>
            <div id="gift-section" class="show-gift-fixed mb-2">
              <%= render partial: 'dashboards/info_send_gift_response', locals: { gifts: @gifts, reply_users: @reply_users } %>
            </div>
          </div>
          <div class="column is-one-third">
            <div id="gifts" class="mb-2">
              <h3>最新の感謝の気持ち</h3>
              <div class="show-info-fixed">
              <% if @latest_gift_messages.present? %>
                <div class="columns is-multiline">
                  <% @latest_gift_messages.each do |entry| %>
                    <div class="column is-full">
                      <div class="card mb-2">
                        <div class="card-content">
                          <div class="content">
                            <p><strong>ギフト名:</strong> <%= entry[:gift].item_name %></p>
                            <% if entry[:gift].image_url.present? %>
                              <%= image_tag asset_path(entry[:gift].image_url), alt: "ギフトの画像", style: "width: 150px;", data: { action: "click->modal#open" } %>
                            <% end %>
                            <p><strong>花言葉or宝石言葉:</strong> <%= entry[:gift].description %></p>
                            <p><strong>送り主:</strong> <%= entry[:gift].anonymous? ? '匿名' : entry[:gift].giver&.name || '不明' %>さん</p>
                            <p><strong>感謝のメッセージ</strong></p>
                            <p><%= entry[:message] %></p>
                            <p><strong>受信日時:</strong> <%= entry[:created_at].in_time_zone('Asia/Tokyo').strftime("%Y-%m-%d %H:%M:%S") %></p>
                            <%
                            app_url = "https://www.xn--z8j3e5a2787akv3apqn.com"
                            tweet_message = "相談のお礼に「#{ERB::Util.url_encode(entry[:gift].item_name)}」を受け取りました！%0A花言葉or宝石言葉:「 #{ERB::Util.url_encode(entry[:gift].description)}」の意味が込められてます。%0A%23めぐる宝石花%0A#{ERB::Util.url_encode(app_url)}"
                            %>
                            <div class="field is-grouped is-grouped-right custom-left buttons-right">
                              <div class="twitter custom-left">
                              <%= link_to "https://twitter.com/intent/tweet?text=#{tweet_message}", target: "_blank", class: "button is-info button-wrap-text ml-2 tooltip", data: { tooltip: "ツイートを投稿" } do %>
                              <i class="fab fa-twitter twitter-icon"></i>
                                <% end %>
                            </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  <% end %>
                </div>
              </div>
              <% else %>
                <p>最新のギフトメッセージはありません。</p>
              <% end %>
            </div>
            <div class="field is-grouped is-grouped-right buttons-right">
              <%= button_to '情報を確認済み', reset_gift_dashboards_path, method: :post, class: 'button is-danger is-small custom-long-left mt-5' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/dashboards/_info_send_gift_response.html.erb
<% if @replies.present? %>
  <% @replies.each do |reply_hash| %>
    <% reply = reply_hash[:reply] %>
    <% if reply.present? && reply.sent_count == 0 %>
      <div id="reply_<%= reply.id %>" class="column is-full">
        <div class="card">
          <div class="card-content p-4">
            <p><strong>返信者:</strong> <%= reply_hash[:display_name] %>さん</p>
            <p><strong>返信内容:</strong> <%= reply_hash[:reply].content %></p>
            <p><em>スタイル: <%= Reply.tones[reply.tone] %></em></p>
            <p><strong>受信日時:</strong> <%= reply.created_at.in_time_zone('Asia/Tokyo').strftime("%Y-%m-%d %H:%M:%S") %></p>
            <br>
            <h4 class="is-size-5">ギフトを選択して<br>メッセージを送ろう</h4>

            <div class="show-fixed">
              <div class="container is-small">
                <div class="columns is-multiline">
                  <% @gifts.each do |gift| %>
                    <div class="column is-full">
                      <div class="card">
                        <div class="card-content">
                          <div class="content">
                            <%= form_with(model: gift, url: send_gift_gift_path(gift), method: :post, data: { turbo_frame: "send_gift_frame_#{gift.id}" }, local: true) do |form| %>
                              <%= hidden_field_tag :return_to, 'info' %>
                              <%= form.hidden_field :receiver_id, value: reply.user_id %>
                              <%= form.hidden_field :reply_id, value: reply.id %>
                              <%= form.hidden_field :anonymous, value: reply.anonymous? %>

                              <div class="card-content p-0">
                                <div class="content p-0">
                                  <p>植物名: <%= gift.item_name %></p>
                                  <% if gift.image_url.present? %>
                                    <%= image_tag asset_path(gift.image_url), alt: "ギフトの画像", style: "width: 150px;", data: { action: "click->modal#open" } %><br>
                                  <% else %>
                                    <%= image_tag "top.png", alt: "デフォルトのギフト画像", style: "width: 150px;" %><br>
                                  <% end %>
                                  <p>花言葉or宝石言葉: <%= gift.description %></p>
                                </div>
                              </div>

                              <div class="field p-0">
                                <%= form.label :sender_message, "感謝のメッセージ", class: 'is-size-6' %>
                                <%= form.text_area :sender_message, class: 'textarea mt-2', placeholder: "ここにメッセージを入力してください", rows: 3 %>
                              </div>

                              <div class="field is-grouped is-grouped-right mt-2">
                                <div class="buttons-right">
                                  <%= form.submit "送る", class: "button is-primary is-small" %>
                                </div>
                              </div>
                            <% end %>
                          </div>
                        </div>
                      </div>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
<% else %>
  <p>返信がありません。</p>
<% end %>

app/views/dashboards/index.html.erb
<div data-controller="modal">
<div class="columns is-mobile is-centered">
  <div class="column is-2 mr-5">
    <div id="menu">
      <%= render "buttons/menu/menu_buttons" %>
    </div>
  </div>
  <div class="column is-flex is-align-items-start">
    <section class="section is-fullheight">
      <div class="container is-flex is-flex-direction-column">
        <div id="content">
          <% if flash[:notice] == 'ユーザーは正常に更新されました。' %>
            <div class="notification is-success info-fixed-error-height ml-5 mb-5">
              <%= flash[:notice] %>
            </div>
          <% end %>
          <%= render "dashboards/info_response", unread_gifts_count: @unread_gifts_count %>
        </div>
      </div>
    </section>
  </div>
</div>

<div data-modal-target="modalContainer" class="modal">
  <div class="modal-background"></div>
    <div class="modal-content">
      <p class="image">
        <img data-modal-target="modalImage" src="" alt="拡大画像" class="is-clickable">
      </p>
    </div>
  <button class="modal-close is-large" aria-label="close" data-action="click->modal#close"></button>
</div>