config/routes.rb
Rails.application.routes.draw do

  # ルートのルーティング
  root 'tops#index'

  get 'anime', to: 'tops#show', as: 'anime' # アニメーションのルーティング
  get 'trial', to: 'trials#index', as: 'trial' # お試しページを表示するためのルーティング

  # top(トップ)のルーティング
  scope :tops, controller: :tops do
    post :tos, as: :tops_tos
    post :pp, as: :tops_pp
    post :enter_app, as: :tops_enter_app
    post :login, as: :tops_login
  end

  # Deviseのルーティング
  devise_for :users, skip: [:sessions], controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    post 'users/auth/google_oauth2/callback', to: 'users/omniauth_callbacks#google_oauth2'
    get '/users/sign_in', to: redirect('/')  # 暫定　ソーシャルログインだけの場合
    delete 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  # dashboard(ダッシュボード)のルーティング
  authenticate :user do
    resources :dashboards, only: [:index] do
      collection do
        post :menu, to: 'dashboards#menu'
        post :close_menu, to: 'dashboards#close_menu'
        post :info, to: 'dashboards#info'
        post :reset_gift, to: 'dashboards#reset_gift_notifications'
      end
    end
  end

  # search(検索)のルーティング
  scope :search, controller: :search do
    post :search_response
    post :search
  end

  # consultation(コンサルテーション)のルーティング
  resources :consultations, only: [:show, :edit, :update, :create, :destroy] do
    member do
      post 'response', to: 'consultations#consultations_response', as: :response
      get 'select_tone', to: 'consultations#select_tone'
    end
  
    collection do
      post 'worries', to: 'consultations#worries'
      post 'detail', to: 'consultations#consultations_detail'
      post 'consultations_category/:category_id', to: 'consultations#consultations_category'
    end
  
    resources :replies, only: [:new, :create, :destroy]
  end

  # gift(ギフト)のルーティング
  resources :gifts do
    collection do
      post 'all', to: 'gifts#gift_all'
      post 'list', to: 'gifts#gift_list'
      post 'send_gift_response', to: 'gifts#send_gift_response'
    end
  
    member do
      patch :mark_as_read
      post 'send_gift', to: 'gifts#send_gift'
    end
  end
  
  resources :menus1, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    collection do
      get :gift_list
    end
  end

  # (chat)チャットのルーティング
  resources :chats, only: [:index, :show, :create, :destroy]  do
    collection do
      post 'chat', to: 'chats#chat'
    end
  end

  # (groupchat)グループチャットのルーティング
  resources :group_chats, only: [:new, :index, :edit, :create, :update, :destroy] do
    member do
      post 'add_member', to: 'group_chats#add_member'
      post 'group_chat', to: 'group_chats#group_chat'
      post 'group_chat_list' , to: 'group_chats#group_chat_list'
    end
    # グループチャットのメンバーのルーティング
    resources :group_chat_members, only: [:new, :create, :update, :destroy]
    # グループチャットのメッセージのルーティング
    resources :group_chat_messages, only: [:create, :destroy]
  end

  #User(ユーザー)のルーティング
  resources :users, only: [:show, :update, :destroy] do
    collection do
      post 'user_list', to: 'users#user_list'
      post 'user_list_show', to: 'users#user_list_show'
    end
    member do
      get 'edit', to: 'users#edit', as: 'edit_user_profile'
    end
  end

  # admin(管理画面)のルート
  authenticate :user, ->(u) { u.super_admin? } do
    namespace :admin do
      resources :users, only: [:destroy]
      resources :consultations, only: [:destroy]
      resources :gifts, only: [:destroy]
      get 'dashboards', to: 'dashboards#index'
      post 'dashboards', to: 'dashboards#redirect_to_dashboard'
      resources :admin_users, only: [:index, :edit, :update, :destroy]
    end
  end
end

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < Admin::ApplicationController
  def index
    @admin_users = AdminUser.includes(:user, :organization).all
    @current_time = Time.zone.now.in_time_zone('Asia/Tokyo')
    @group_chats = GroupChat.all
    @users = User.all
    @consultations = Consultation.all
    @gifts = Gift.includes(:gift_category).all
    @gift_histories = GiftHistory.all
    @gift_templates = GiftTemplate.includes(:gift_category).all
  end

  def destroy_user
    user = User.find(params[:id])
    user.destroy
    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove(dom_id(user)) }
      format.html { redirect_to admin_dashboards_index_path, notice: 'ユーザーを削除しました。' }
    end
  end

  def destroy_consultation
    consultation = Consultation.find(params[:id])
    consultation.destroy
    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove(dom_id(consultation)) }
      format.html { redirect_to admin_dashboards_index_path, notice: '相談を削除しました。' }
    end
  end

  def destroy_gift
    gift = Gift.find(params[:id])
    gift.destroy
    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove(dom_id(gift)) }
      format.html { redirect_to admin_dashboards_index_path, notice: 'ギフトを削除しました。' }
    end
  end

  def redirect_to_dashboard
    redirect_to admin_dashboard_path
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :set_common_variables, only: [:index, :info, :menu, :close_menu]
  before_action :set_latest_replies_and_notifications, only: [:index, :info]

  def index; end

  def info
    @current_time = Time.zone.now
    render_turbo_response("content", "info_response", {
      gifts: @gifts,
      replies: @replies,
      reply_users: @reply_users,
      latest_gift_messages: @latest_gift_messages,
      unread_gifts_count: @unread_gifts_count,
      unread_replies_count: @unread_replies_count,
      current_time: @current_time,
      group_chats: @group_chats,
      user: @user,
      latest_gifts: @latest_gifts,
      sent_gifts: @sent_gifts,
      received_gifts: @received_gifts
    })
  end

  def menu
    render_turbo_stream_for_menu("buttons/menu/menu_buttons")
  end

  def close_menu
    render_turbo_stream_for_menu("buttons/menu/closed_menu")
  end

  def search
    if params[:query].present? && params[:query].strip.present?
      queries = params[:query].split(/[\s　]+/)
      @consultations = queries.flat_map do |q|
        Consultation.search(q, fields: [:title, :content, :category_name, :user_name], match: :word_middle)
      end.uniq
    else
      @consultations = Consultation.none
    end
  end

  def reset_gift_notifications
    replier_ids = current_user.consultations.joins(:replies).pluck('replies.user_id').uniq
    @received_gifts_from_repliers = current_user.received_gifts.where(giver_id: replier_ids)
    mark_gift_comments_and_messages_as_read(@received_gifts_from_repliers)
    redirect_to dashboards_path, notice: '通知がリセットされました。'
  end

  private

  def set_common_variables
    @user = current_user
    @unread_gifts_count = @user.calculate_unread_gifts_count
    @unread_replies_count = fetch_unread_replies_count
    @gifts = @user.received_gifts
    @reply_users = User.joins(:replies).distinct
    @latest_gifts = Gift.order(created_at: :desc).limit(5)
    @sent_gifts = @user.sent_gifts
    @received_gifts = @user.received_gifts
    @latest_gift_messages = fetch_latest_gift_messages
    @group_chats = GroupChat.all
    @available_gift_items = @user.received_gifts.where(sent_at: nil).distinct.pluck(:item_name)
    
    @replies = fetch_latest_replies.map do |reply|
      {
        reply: reply,
        display_name: reply.display_name
      }
    end
  end

  def set_latest_replies_and_notifications
    @latest_replies = fetch_latest_replies
  end

  def fetch_latest_replies
    Reply.joins(:consultation, :user)
         .where(consultations: { user_id: current_user.id })
         .select('replies.*, users.name as user_name')
         .order('replies.created_at DESC')
         .limit(5)
  end

  def fetch_latest_gift_messages
    gift_messages = current_user.received_gifts.joins(:gift_histories).pluck('gift_histories.sender_message', 'gift_histories.created_at', 'gifts.id') +
                    current_user.received_gifts.pluck(:sender_message, :created_at, :id)
    gift_messages.reject { |message, _, _| message.blank? }
                 .sort_by { |_, created_at, _| created_at }
                 .reverse
                 .first(5)
                 .map do |message, created_at, gift_id|
                   gift = Gift.find(gift_id)
                   { message: message, created_at: created_at, gift: Gift.find(gift_id) }
                 end
  end

  def fetch_unread_replies_count
    current_user.consultations.joins(:replies).where(replies: { read: false }).count || 0
  end

  def mark_gift_comments_and_messages_as_read(gifts)
    gifts.each do |gift|
      gift.gift_histories.where(read: false).update_all(read: true)
      gift.update(sender_message: nil) if gift.sender_message.present?
    end
  end

  def render_turbo_response(target, partial, locals = {})
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace(target, partial: partial, locals: locals)
      end
    end
  end

  def render_turbo_stream_for_menu(menu_partial)
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.replace("menu", partial: menu_partial),
          turbo_stream.replace("content", partial: "buttons/response"),
          turbo_stream.replace('unread-replies-count', partial: 'layouts/unread_replies_count', locals: { user: current_user }),
          turbo_stream.replace("unread-gifts-count", partial: "layouts/unread_gifts_count", locals: { unread_gifts_count: @unread_gifts_count })
        ]
      end
    end
  end
end

app/views/admin/dashboards/_admin_button.erb
<%= button_to '管理者画面', admin_dashboards_path, method: :get, data: { turbo: true }, class: 'button is-danger is-small custom-long-left mt-5' %>

app/views/admin/dashboards/_consultations_index.html.erb
<div class="column is-full">
  <div class="level">
    <div class="level-left">
      <h2 class="subtitle">相談一覧: 全<%= consultations.count %>件</h2>
    </div>
  </div>
</div>
<div class="columns is-multiline">
  <% consultations.each do |consultation| %>
    <div class="column is-one-third" id="<%= dom_id(consultation) %>">
      <div class="box">
        <p class="title is-4"><%= consultation.title %></p>
        <% if current_user.super_admin? || current_user.admin? %>
          <div class="are-small has-text-right">
            <%= button_to '削除', admin_consultation_path(consultation), method: :delete, data: { turbo_confirm: '本当にこの相談を削除しますか？' }, remote: true, form: { data: { turbo: true }, class: 'button is-danger' } %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/dashboards/_gift_templates_index.html.erb
<div class="column is-full">
  <div class="level">
    <div class="level-left">
      <h2 class="subtitle">ギフトテンプレート一覧: 全<%= gift_templates.count %>件</h2>
    </div>
  </div>
</div>
<div class="columns is-multiline">
  <% gift_templates.each do |template| %>
    <div id="gift_card_<%= template.id %>" class="column is-one-third">
      <div class="card">
        <header class="card-header">
          <p class="card-header-title">
            カテゴリ: <%= template.gift_category.name %>
          </p>
        </header>
        <div class="card-content">
          <div class="content">
            植物名: <%= template.name %><br>
            <%= image_tag asset_path(template.image_url), alt: "ギフトの画像", style: "width: 200px;" %><br>
            花言葉or宝石言葉: <%= template.description %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/dashboards/_gifts_index.html.erb
<div class="column is-full">
  <div class="level">
    <div class="level-left">
      <h2 class="subtitle">ギフト一覧: 全<%= gifts.count %>件</h2>
    </div>
  </div>
</div>
<div class="columns is-multiline">
  <% gifts.each do |gift| %>
    <div class="column is-full-mobile is-one-third-tablet" id="<%= dom_id(gift) %>">
      <div class="box">
      <p class="title is-4"><%= gift.item_name %></p>
        <% if current_user.super_admin? || current_user.admin? %>
          <div class="are-small has-text-right">
            <%= button_to '削除', admin_gift_path(gift), method: :delete, data: { turbo_confirm: '本当にこのギフトを削除しますか？' }, remote: true, form: { data: { turbo: true }, class: 'button is-danger' } %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/dashboards/_sended_gifts_index.html.erb
<div class="column is-full">
  <div class="level">
    <div class="level-left">
      <h2 class="subtitle">送信済ギフト一覧: 全<%= gift_histories.count %>件</h2>
    </div>
  </div>
</div>
<div class="columns is-multiline">
  <% gift_histories.each do |history| %>
    <div class="column is-full-mobile is-one-third-tablet" id="<%= dom_id(history) %>">
      <div class="card">
        <div class="card-content">
        <% sended_gift = Gift.find_by(id: history.gift_id) %>
        <p class="title is-4">ギフト名:</p>
        <p class="subtitle is-flex my-2">
          <% if sended_gift.present? %>
            <%= sended_gift.item_name %>
          <% else %>
            ギフトが見つかりません
          <% end %>
        </p>
        <p class="title is-4">メッセージ内容:</p>
        <p class="subtitle is-flex my-2"><%= history.sender_message %></p>
        <% if current_user.super_admin? || current_user.admin? %>
          <div class="are-small has-text-right">
            <%= button_to '削除', "#", method: :delete, data: { turbo_confirm: '本当にこのメッセージを削除しますか？' }, remote: true, form: { data: { turbo: true }, class: 'button is-danger' } %>
          </div>
        <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/dashboards/_users_index.html.erb
<div class="column is-full">
  <div class="level">
    <div class="level-left">
      <h2 class="subtitle">ユーザー一覧: 全<%= users.count %>件</h2>
    </div>
  </div>
</div>
<div class="columns is-multiline user-list-heigth">
  <% users.each do |user| %>
    <div class="column is-full-mobile is-one-third-tablet" id="<%= dom_id(user) %>">
      <div class="card">
        <div class="card-content">
          <p class="title is-4">ユーザー名: <%= user.name %></p>
          <p class="title is-4">チャット名: <%= user.display_name %></p>
          <% if current_user.super_admin? || current_user.admin? %>
            <div class="are-small has-text-right">
              <%= button_to '削除', admin_user_path(user), method: :delete, data: { turbo_confirm: '本当にこのユーザーを削除しますか？' }, remote: true, form: { data: { turbo: true }, class: 'button is-danger' } %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/dashboards/destroy_consultation.turbo_stream.erb
<%= turbo_stream.remove dom_id(@consultation) %>

app/views/admin/dashboards/destroy_gift.turbo_stream.erb
<%= turbo_stream.remove dom_id(@gift) %>

app/views/admin/dashboards/destroy_user.turbo_stream.erb
<%= turbo_stream.remove dom_id(@user) %>

app/views/admin/dashboards/index.html.erb
<% if current_user.super_admin? || current_user.admin? %>
  <div id="content" class="frame-fixed-height container is-small mb-3">
    <div class="is-flex m-5">
      <h1 class="title">管理者ダッシュボード</h1>
      <%= link_to 'ダッシュボードに戻る', dashboards_path, class: 'button is-info ml-5' %>
    </div>
    <div class="has-text-right m-10">
      <%= button_to '管理者ユーザー一覧へ', admin_admin_users_path, method: :get, data: { turbo: true }, class: 'button is-primary ml-2' %>
    </div>
  </div>
<% end %>
  
<div id="content" class="frame-fixed-height container is-small mb-3">
  <div class="admin-user-list">
    <%= render "users_index", users: @users %>
  </div>
</div>

<div id="content" class="frame-fixed-height container is-small mb-3">
  <div class="consultation-list">
    <%= render "consultations_index", consultations: @consultations %>
  </div>
</div>

<div id="content" class="frame-fixed-height container is-small mb-3">
  <div class="admin-gift-list">
    <%= render "sended_gifts_index", gift_histories: @gift_histories %>
  </div>
</div>

<div id="content" class="frame-fixed-height container is-small mb-3">
  <div class="admin-gift-list">
    <%= render "gifts_index", gifts: @gifts %>
  </div>
</div>
  
<div id="content" class="container is-small gift-list-height">
  <div class="admin-gift-templates-list">
    <%= render "gift_templates_index", gift_templates: @gift_templates %>
  </div>
</div>